<?php
namespace Shopping\Controller;
use App\Controller\AppController;
use Cake\Event\Event;

class CartsController extends AppController {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadModel('Shopping.Carts');
        $this->loadModel('Shopping.Products');
    }

    public function add($product_id = null)
    {
        $this->autoRender = false;
        if ($product_id != null) {
            $this->Carts->addProduct($product_id);
            echo $this->Carts->getCount();
        }
    }

    public function view()
    {
        $carts = $this->Carts->readProduct();
        $products = [];
        if (null != $carts) {
            foreach ($carts as $productId => $count) {
                $product = $this->Products->get($productId);
                $product->count = $count;
                $products[] = $product;
            }
        }
        $this->set(compact('products'));
    }

    public function update() {
        if ($this->request->is('post')) {
            debug($this->request->getData());
            if (!empty($this->request->getData())) {
                $cart = [];
                foreach ($this->request->getData('count') as $index => $count) {
                    if ($count > 0) {
                        $productId = $this->request->getData('product_id');
                        $cart[$productId] = $count;
                    }
                }
                $this->Carts->saveProduct($cart);
            }
        }
        $this->redirect(['action' =>'view']);
    }
}